### ISSUE TITLE
Preprocessor #if-#endif coloring

### ISSUE THREAD

**Issue by CoreyCoop** [Benio101/Color.Comment#6]
# Feature request
### Short Description
This used to be available in PowerTools from MS, but it 'broke' in VS 2019.  No one has done it yet, but it looks like this would be a 'simple' :-) add to this project.
When you have multiple configurations in your code, and they are selected in C++ for instance with
#if blaba
(It won't let me put # with endif)
then when the code inside the block is disabled, it can be set to a different color, grayed out.

### Relevance
used in C#, C and C++, possibly others.

**Comment by Benio101** [comment]
You should be possible to achieve this by adding the attribute `[Order(Before = "excluded code")]` to each of demanded colors in a [Style.cs](https://github.com/Benio101/Color.Comment/blob/master/Color.Comment/Style.cs) file.
Unfortunatelly, I've abandoned the project so I'm changing status to `Won't fix` as I abandon the project.
